name: 'Deploy to AWS S3'
description: 'rewrgthgtrgtr'
inputs:
  bucket:
    description: 'the s3 bucket name'
    required: true
  bucket-region:
    description: 'dsf '
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'folder'
    required: true
runs:
  using: 'node16'
  main: 'main.js'